### ISSUE TITLE
Cannot bind argument to parameter 'DifferenceObject' because it is null.

### ISSUE THREAD

**Issue by tomasfil** [angelics/SephMiner#3]
[SephMiner_2018-04-20_08-51-52.txt](https://github.com/angelics/SephMiner/files/1931050/SephMiner_2018-04-20_08-51-52.txt)

**Comment by angelics** [comment]
line 270 @ refering to type. do you remove type that you do no use in start.bat?
my mining rigs r fine here

edit:wrong line ref

**Comment by tomasfil** [comment]
I have there only amd at the type
[Start-MiningPoolHub.txt](https://github.com/angelics/SephMiner/files/1931123/Start-MiningPoolHub.txt)

**Comment by angelics** [comment]
i made another commit for ewbf. i guess its causing the problem. as i moved ewbf to disable folder inside miner. u'll wan to move unused miner and pool files to disable folder too. especially slow cpu. plz close if solved

**Comment by tomasfil** [comment]
That last commit solved it. Thanks.
